sudo: required

services:
  - docker

language: bash

script:
# login to docker hub
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# arm docker build and push
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- docker build -t tribunex/git-pull-pi:latest .
- docker push tribunex/git-pull-pi:latest