sudo: required

services:
  - docker

language: bash

script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset

# get qemu-arm-static binary
- mkdir tmp
- >
  pushd tmp &&
  curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-2/qemu-arm-static.tar.gz &&
  tar xzf qemu-arm-static.tar.gz &&
  popd

# arm docker build and push
- docker build -t tribunex/git-pull-pi:latest .

# login to docker hub
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push tribunex/git-pull-pi:latest